"""add queue_id to ivr_nodes

Revision ID: 90cd98a7506f
Revises: 
Create Date: 2026-03-19 09:27:50.939306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90cd98a7506f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ivr_nodes', sa.Column('queue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ivr_nodes', 'queues', ['queue_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user_status', 'login_status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('LOGIN', 'LOGOUT', name='loginstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'LOGOUT'::character varying"))
    op.alter_column('user_status_log', 'login_status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('LOGIN', 'LOGOUT', name='loginstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_status_log', 'login_status',
               existing_type=sa.Enum('LOGIN', 'LOGOUT', name='loginstatus', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
    op.alter_column('user_status', 'login_status',
               existing_type=sa.Enum('LOGIN', 'LOGOUT', name='loginstatus', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False,
               existing_server_default=sa.text("'LOGOUT'::character varying"))
    op.drop_constraint(None, 'ivr_nodes', type_='foreignkey')
    op.drop_column('ivr_nodes', 'queue_id')
    # ### end Alembic commands ###
